spring:
  datasource:
    url: jdbc:postgresql://gondola.proxy.rlwy.net:47582/railway
    username: postgres
    password: MhjFVUvDAZjxxNNCbFBuHMqEwlftgzdu

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.authmanagement: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

app:
  jwt:
    secret: devSecretKey123456789012345678901234567890123456789012345678901234567890
    expiration: 3600  # 1 hora para desarrollo
    refresh-expiration: 86400  # 1 día para desarrollo

